version: "3.8"

services:
  producer:
    build:
      context: ./js-producer
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
  consumer:
    build:
      context: ./js-consumer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ETH0_IP=${ETH0_IP}
